// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyATt5BrsVosHdDzOYCyQ8qMCJx6egEAAsQ',
    appId: '1:472133318535:web:f55a0fca2377dd6505c522',
    messagingSenderId: '472133318535',
    projectId: 'fir-test-user-auth',
    authDomain: 'fir-test-user-auth.firebaseapp.com',
    storageBucket: 'fir-test-user-auth.firebasestorage.app',
    measurementId: 'G-YBHJTECLR0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAj6bnjOP5hY13auky4fWyu3muk4emC6eA',
    appId: '1:472133318535:android:1391ccc4c9a4f48905c522',
    messagingSenderId: '472133318535',
    projectId: 'fir-test-user-auth',
    storageBucket: 'fir-test-user-auth.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDHjg_Ng9Wm-mbbh0CsHzTcPIIY3D8D_Bk',
    appId: '1:472133318535:ios:d5c32d156f4b0eb605c522',
    messagingSenderId: '472133318535',
    projectId: 'fir-test-user-auth',
    storageBucket: 'fir-test-user-auth.firebasestorage.app',
    iosBundleId: 'com.example.firebaseTestApi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDHjg_Ng9Wm-mbbh0CsHzTcPIIY3D8D_Bk',
    appId: '1:472133318535:ios:d5c32d156f4b0eb605c522',
    messagingSenderId: '472133318535',
    projectId: 'fir-test-user-auth',
    storageBucket: 'fir-test-user-auth.firebasestorage.app',
    iosBundleId: 'com.example.firebaseTestApi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyATt5BrsVosHdDzOYCyQ8qMCJx6egEAAsQ',
    appId: '1:472133318535:web:827278b1ee0b2eae05c522',
    messagingSenderId: '472133318535',
    projectId: 'fir-test-user-auth',
    authDomain: 'fir-test-user-auth.firebaseapp.com',
    storageBucket: 'fir-test-user-auth.firebasestorage.app',
    measurementId: 'G-6WWF3P1JBV',
  );
}
